name: 'InclusiveCopywriting'
description: 'Scan paths/files for words you do not want to be used'
inputs:
  include_paths:
    description: 'Paths to check'
    required: true
  exclude_words:
    description: 'Disallowed Words'
    required: true
  file_types:
    description: 'File types to scan'
  warnings_as_errors:
    description: 'Should found words be reported as an error'
    default: true
outputs:
  files_with_errors:
    description: 'Files containing non-inclusive words'
runs:
  using: 'node16'
  main: 'index.js'